language: node_js
node_js:
  - "10.15"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

install:
  - yarn install --frozen-lockfile --non-interactive

jobs:
  include:
    - name: Test
      script:
        - yarn run test
